// Interface automatically generated by schemas-to-ts

export interface Test {
  id: number;
  attributes: {
    TestName?: string;
    TestNumber?: number;
  };
}
export interface Test_Plain {
  id: number;
  TestName?: string;
  TestNumber?: number;
}

export interface Test_NoRelations {
  id: number;
  TestName?: string;
  TestNumber?: number;
}

export interface Test_AdminPanelLifeCycle {
  id: number;
  TestName?: string;
  TestNumber?: number;
}
